// customer.subscription.created

const _event = {
    id: "evt_1Sou5ZA4zKrgX9zsAQXVcXF9",
    object: "event",
    api_version: "2025-12-15.clover",
    created: 1768258796,
    data: {
        object: {
            id: "sub_1Sou5YA4zKrgX9zsveCMpZ3c",
            object: "subscription",
            application: null,
            application_fee_percent: null,
            automatic_tax: { disabled_reason: null, enabled: false, liability: null },
            billing_cycle_anchor: 1769468395,
            billing_cycle_anchor_config: null,
            billing_mode: {
                flexible: { proration_discounts: "included" },
                type: "flexible",
                updated_at: 1768258767,
            },
            billing_thresholds: null,
            cancel_at: null,
            cancel_at_period_end: false,
            canceled_at: null,
            cancellation_details: { comment: null, feedback: null, reason: null },
            collection_method: "charge_automatically",
            created: 1768258795,
            currency: "usd",
            customer: "cus_TmT1XYNgI8vPsS",
            customer_account: null,
            days_until_due: null,
            default_payment_method: "pm_1Sou5WA4zKrgX9zs6e9LWUUE",
            default_source: null,
            default_tax_rates: [],
            description: null,
            discounts: [],
            ended_at: null,
            invoice_settings: { account_tax_ids: null, issuer: { type: "self" } },
            items: {
                object: "list",
                data: [[Object]],
                has_more: false,
                total_count: 1,
                url: "/v1/subscription_items?subscription=sub_1Sou5YA4zKrgX9zsveCMpZ3c",
            },
            latest_invoice: "in_1Sou5XA4zKrgX9zsXIcRnoLc",
            livemode: false,
            metadata: {},
            next_pending_invoice_item_invoice: null,
            on_behalf_of: null,
            pause_collection: null,
            payment_settings: {
                payment_method_options: {
                    acss_debit: null,
                    bancontact: null,
                    card: [Object],
                    customer_balance: null,
                    konbini: null,
                    payto: null,
                    sepa_debit: null,
                    us_bank_account: null,
                },
                payment_method_types: null,
                save_default_payment_method: "off",
            },
            pending_invoice_item_interval: null,
            pending_setup_intent: null,
            pending_update: null,
            plan: {
                id: "price_1SoY5AA4zKrgX9zsYJ9ZgNJ7",
                object: "plan",
                active: true,
                amount: 1500,
                amount_decimal: "1500",
                billing_scheme: "per_unit",
                created: 1768174204,
                currency: "usd",
                interval: "month",
                interval_count: 1,
                livemode: false,
                metadata: {},
                meter: null,
                nickname: "Pro (Monthly)",
                product: "prod_Tm6H25iEKp9ZRs",
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: "licensed",
            },
            quantity: 1,
            schedule: null,
            start_date: 1768258795,
            status: "trialing",
            test_clock: null,
            transfer_data: null,
            trial_end: 1769468395,
            trial_settings: { end_behavior: { missing_payment_method: "pause" } },
            trial_start: 1768258795,
        },
    },
    livemode: false,
    pending_webhooks: 1,
    request: { id: null, idempotency_key: "1fe8f21e-f52f-4628-b5b4-15436ca97818" },
    type: "customer.subscription.created",
}

const _subscription = {
    id: "sub_1Sou5YA4zKrgX9zsveCMpZ3c",
    object: "subscription",
    application: null,
    application_fee_percent: null,
    automatic_tax: { disabled_reason: null, enabled: false, liability: null },
    billing_cycle_anchor: 1769468395,
    billing_cycle_anchor_config: null,
    billing_mode: {
        flexible: { proration_discounts: "included" },
        type: "flexible",
        updated_at: 1768258767,
    },
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: { comment: null, feedback: null, reason: null },
    collection_method: "charge_automatically",
    created: 1768258795,
    currency: "usd",
    customer: "cus_TmT1XYNgI8vPsS",
    customer_account: null,
    days_until_due: null,
    default_payment_method: "pm_1Sou5WA4zKrgX9zs6e9LWUUE",
    default_source: null,
    default_tax_rates: [],
    description: null,
    discounts: [],
    ended_at: null,
    invoice_settings: { account_tax_ids: null, issuer: { type: "self" } },
    items: {
        object: "list",
        data: [
            {
                id: "si_TmT16BCzcACUlu",
                object: "subscription_item",
                billing_thresholds: null,
                created: 1768258795,
                current_period_end: 1769468395,
                current_period_start: 1768258795,
                discounts: [],
                metadata: {},
                plan: {
                    id: "price_1SoY5AA4zKrgX9zsYJ9ZgNJ7",
                    object: "plan",
                    active: true,
                    amount: 1500,
                    amount_decimal: "1500",
                    billing_scheme: "per_unit",
                    created: 1768174204,
                    currency: "usd",
                    interval: "month",
                    interval_count: 1,
                    livemode: false,
                    metadata: {},
                    meter: null,
                    nickname: "Pro (Monthly)",
                    product: "prod_Tm6H25iEKp9ZRs",
                    tiers_mode: null,
                    transform_usage: null,
                    trial_period_days: null,
                    usage_type: "licensed",
                },
                price: {
                    id: "price_1SoY5AA4zKrgX9zsYJ9ZgNJ7",
                    object: "price",
                    active: true,
                    billing_scheme: "per_unit",
                    created: 1768174204,
                    currency: "usd",
                    custom_unit_amount: null,
                    livemode: false,
                    lookup_key: null,
                    metadata: {},
                    nickname: "Pro (Monthly)",
                    product: "prod_Tm6H25iEKp9ZRs",
                    recurring: [Object],
                    tax_behavior: "unspecified",
                    tiers_mode: null,
                    transform_quantity: null,
                    type: "recurring",
                    unit_amount: 1500,
                    unit_amount_decimal: "1500",
                },
                quantity: 1,
                subscription: "sub_1Sou5YA4zKrgX9zsveCMpZ3c",
                tax_rates: [],
            },
        ],
        has_more: false,
        total_count: 1,
        url: "/v1/subscription_items?subscription=sub_1Sou5YA4zKrgX9zsveCMpZ3c",
    },
    latest_invoice: "in_1Sou5XA4zKrgX9zsXIcRnoLc",
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
        payment_method_options: {
            acss_debit: null,
            bancontact: null,
            card: { network: null, request_three_d_secure: "automatic" },
            customer_balance: null,
            konbini: null,
            payto: null,
            sepa_debit: null,
            us_bank_account: null,
        },
        payment_method_types: null,
        save_default_payment_method: "off",
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
        id: "price_1SoY5AA4zKrgX9zsYJ9ZgNJ7",
        object: "plan",
        active: true,
        amount: 1500,
        amount_decimal: "1500",
        billing_scheme: "per_unit",
        created: 1768174204,
        currency: "usd",
        interval: "month",
        interval_count: 1,
        livemode: false,
        metadata: {},
        meter: null,
        nickname: "Pro (Monthly)",
        product: "prod_Tm6H25iEKp9ZRs",
        tiers_mode: null,
        transform_usage: null,
        trial_period_days: null,
        usage_type: "licensed",
    },
    quantity: 1,
    schedule: null,
    start_date: 1768258795,
    status: "trialing",
    test_clock: null,
    transfer_data: null,
    trial_end: 1769468395,
    trial_settings: { end_behavior: { missing_payment_method: "pause" } },
    trial_start: 1768258795,
}
