// customer.subscription.deleted
const _event = {
    id: "evt_1SoftWA4zKrgX9zsHZraIchy",
    object: "event",
    api_version: "2025-12-15.clover",
    created: 1768204234,
    data: {
        object: {
            id: "sub_1Sofl8A4zKrgX9zsBugAFIeg",
            object: "subscription",
            application: null,
            application_fee_percent: null,
            automatic_tax: { disabled_reason: null, enabled: false, liability: null },
            billing_cycle_anchor: 1774494957,
            billing_cycle_anchor_config: null,
            billing_mode: {
                flexible: { proration_discounts: "included" },
                type: "flexible",
                updated_at: 1774494957,
            },
            billing_thresholds: null,
            cancel_at: 1775099757,
            cancel_at_period_end: true,
            canceled_at: 1774494957,
            cancellation_details: {
                comment: null,
                feedback: null,
                reason: "cancellation_requested",
            },
            collection_method: "charge_automatically",
            created: 1774494957,
            currency: "usd",
            customer: "cus_Tm9Ns6FxDSz3r7",
            customer_account: null,
            days_until_due: null,
            default_payment_method: null,
            default_source: null,
            default_tax_rates: [],
            description: null,
            discounts: [],
            ended_at: 1775099757,
            invoice_settings: { account_tax_ids: null, issuer: { type: "self" } },
            items: {
                object: "list",
                data: [[Object]],
                has_more: false,
                total_count: 1,
                url: "/v1/subscription_items?subscription=sub_1Sofl8A4zKrgX9zsBugAFIeg",
            },
            latest_invoice: "in_1Sofl8A4zKrgX9zsXTqqew00",
            livemode: false,
            metadata: {},
            next_pending_invoice_item_invoice: null,
            on_behalf_of: null,
            pause_collection: null,
            payment_settings: {
                payment_method_options: null,
                payment_method_types: null,
                save_default_payment_method: "off",
            },
            pending_invoice_item_interval: null,
            pending_setup_intent: "seti_1Sofl9A4zKrgX9zshndr0lOY",
            pending_update: null,
            plan: {
                id: "price_1SoY5AA4zKrgX9zscje8hTVI",
                object: "plan",
                active: true,
                amount: 0,
                amount_decimal: "0",
                billing_scheme: "per_unit",
                created: 1768174204,
                currency: "usd",
                interval: "week",
                interval_count: 1,
                livemode: false,
                metadata: {},
                meter: null,
                nickname: "Free",
                product: "prod_Tm6H25iEKp9ZRs",
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: "licensed",
            },
            quantity: 1,
            schedule: null,
            start_date: 1774494957,
            status: "canceled",
            test_clock: "clock_1SobbrA4zKrgX9zsnjIVVN23",
            transfer_data: null,
            trial_end: null,
            trial_settings: { end_behavior: { missing_payment_method: "create_invoice" } },
            trial_start: null,
        },
    },
    livemode: false,
    pending_webhooks: 1,
    request: { id: null, idempotency_key: null },
    type: "customer.subscription.deleted",
}
