// new subscription with checkout session
const _ = {
    id: "evt_1SoahKA4zKrgX9zsGM0tNsNY",
    object: "event",
    api_version: "2025-12-15.clover",
    created: 1768184258,
    data: {
        object: {
            id: "cs_test_a1fu8eoTAFjT8yRRTQPEy2fj44afzujbnI3mda8WsDEHavpngTNJENjyhy",
            object: "checkout.session",
            adaptive_pricing: { enabled: false },
            after_expiration: null,
            allow_promotion_codes: null,
            amount_subtotal: 0,
            amount_total: 0,
            automatic_tax: { enabled: false, liability: null, provider: null, status: null },
            billing_address_collection: null,
            branding_settings: {
                background_color: "#ffffff",
                border_style: "rounded",
                button_color: "#0074d4",
                display_name: "Environnement de test Super Panda",
                font_family: "default",
                icon: null,
                logo: null,
            },
            cancel_url: null,
            client_reference_id: "8a5e6f4c-5229-4808-94b6-ed3f3a36b8b7",
            client_secret: null,
            collected_information: {
                business_name: null,
                individual_name: null,
                shipping_details: null,
            },
            consent: null,
            consent_collection: null,
            created: 1768184225,
            currency: "usd",
            currency_conversion: null,
            custom_fields: [],
            custom_text: {
                after_submit: null,
                shipping_address: null,
                submit: null,
                terms_of_service_acceptance: null,
            },
            customer: "cus_Tm8zKuiHlbrSuk",
            customer_account: null,
            customer_creation: "always",
            customer_details: {
                address: {
                    city: null,
                    country: "JP",
                    line1: null,
                    line2: null,
                    postal_code: null,
                    state: null,
                },
                business_name: null,
                email: "itsuki.enjoy@gmail.com",
                individual_name: null,
                name: "123",
                phone: null,
                tax_exempt: "none",
                tax_ids: [],
            },
            customer_email: "itsuki.enjoy@gmail.com",
            discounts: [],
            expires_at: 1768270625,
            invoice: "in_1SoahHA4zKrgX9zsSb1fHL9a",
            invoice_creation: null,
            livemode: false,
            locale: null,
            metadata: {},
            mode: "subscription",
            origin_context: null,
            payment_intent: null,
            payment_link: null,
            payment_method_collection: "always",
            payment_method_configuration_details: { id: "pmc_1So9qqA4zKrgX9zsNPF10nES", parent: null },
            payment_method_options: { card: { request_three_d_secure: "automatic" } },
            payment_method_types: ["card", "link", "amazon_pay"],
            payment_status: "paid",
            permissions: null,
            phone_number_collection: { enabled: false },
            recovered_from: null,
            saved_payment_method_options: {
                allow_redisplay_filters: ["always"],
                payment_method_remove: "disabled",
                payment_method_save: null,
            },
            setup_intent: null,
            shipping_address_collection: null,
            shipping_cost: null,
            shipping_options: [],
            status: "complete",
            submit_type: null,
            subscription: "sub_1SoahJA4zKrgX9zsZ5pKaSnK",
            success_url: "https://dummy",
            total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
            ui_mode: "hosted",
            url: null,
            wallet_options: null,
        },
    },
    livemode: false,
    pending_webhooks: 1,
    request: { id: null, idempotency_key: null },
    type: "checkout.session.completed",
}

const _subscription = {
    id: "sub_1SogFZA4zKrgX9zstICaCQL3",
    object: "subscription",
    application: null,
    application_fee_percent: null,
    automatic_tax: { disabled_reason: null, enabled: false, liability: null },
    billing_cycle_anchor: 1769415200,
    billing_cycle_anchor_config: null,
    billing_mode: {
        flexible: { proration_discounts: "included" },
        type: "flexible",
        updated_at: 1768205586,
    },
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: { comment: null, feedback: null, reason: null },
    collection_method: "charge_automatically",
    created: 1768205600,
    currency: "usd",
    customer: "cus_TmEjpVOlaf0xVD",
    customer_account: null,
    days_until_due: null,
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discounts: [],
    ended_at: null,
    invoice_settings: { account_tax_ids: null, issuer: { type: "self" } },
    items: {
        object: "list",
        data: [
            {
                id: "si_TmEja902vMstww",
                object: "subscription_item",
                billing_thresholds: null,
                created: 1768205600,
                current_period_end: 1769415200,
                current_period_start: 1768205600,
                discounts: [],
                metadata: {},
                plan: {
                    id: "price_1SoY5AA4zKrgX9zsYJ9ZgNJ7",
                    object: "plan",
                    active: true,
                    amount: 1500,
                    amount_decimal: "1500",
                    billing_scheme: "per_unit",
                    created: 1768174204,
                    currency: "usd",
                    interval: "month",
                    interval_count: 1,
                    livemode: false,
                    metadata: {},
                    meter: null,
                    nickname: "Pro (Monthly)",
                    product: "prod_Tm6H25iEKp9ZRs",
                    tiers_mode: null,
                    transform_usage: null,
                    trial_period_days: null,
                    usage_type: "licensed",
                },
                price: {
                    id: "price_1SoY5AA4zKrgX9zsYJ9ZgNJ7",
                    object: "price",
                    active: true,
                    billing_scheme: "per_unit",
                    created: 1768174204,
                    currency: "usd",
                    custom_unit_amount: null,
                    livemode: false,
                    lookup_key: null,
                    metadata: {},
                    nickname: "Pro (Monthly)",
                    product: "prod_Tm6H25iEKp9ZRs",
                    recurring: [Object],
                    tax_behavior: "unspecified",
                    tiers_mode: null,
                    transform_quantity: null,
                    type: "recurring",
                    unit_amount: 1500,
                    unit_amount_decimal: "1500",
                },
                quantity: 1,
                subscription: "sub_1SogFZA4zKrgX9zstICaCQL3",
                tax_rates: [],
            },
        ],
        has_more: false,
        total_count: 1,
        url: "/v1/subscription_items?subscription=sub_1SogFZA4zKrgX9zstICaCQL3",
    },
    latest_invoice: "in_1SogFYA4zKrgX9zsfngMLpBT",
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
        payment_method_options: {
            acss_debit: null,
            bancontact: null,
            card: { network: null, request_three_d_secure: "automatic" },
            customer_balance: null,
            konbini: null,
            payto: null,
            sepa_debit: null,
            us_bank_account: null,
        },
        payment_method_types: null,
        save_default_payment_method: "off",
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
        id: "price_1SoY5AA4zKrgX9zsYJ9ZgNJ7",
        object: "plan",
        active: true,
        amount: 1500,
        amount_decimal: "1500",
        billing_scheme: "per_unit",
        created: 1768174204,
        currency: "usd",
        interval: "month",
        interval_count: 1,
        livemode: false,
        metadata: {},
        meter: null,
        nickname: "Pro (Monthly)",
        product: "prod_Tm6H25iEKp9ZRs",
        tiers_mode: null,
        transform_usage: null,
        trial_period_days: null,
        usage_type: "licensed",
    },
    quantity: 1,
    schedule: null,
    start_date: 1768205600,
    status: "trialing",
    test_clock: null,
    transfer_data: null,
    trial_end: 1769415200,
    trial_settings: { end_behavior: { missing_payment_method: "cancel" } },
    trial_start: 1768205600,
}
