const _ = {
    id: "evt_1SoHN9A4zKrgX9zs7LdzScAr",
    object: "event",
    api_version: "2025-12-15.clover",
    created: 1768109971,
    data: {
        object: {
            id: "sub_1SoHN8A4zKrgX9zsVRER5MB7",
            object: "subscription",
            application: null,
            application_fee_percent: null,
            automatic_tax: { disabled_reason: null, enabled: false, liability: null },
            billing_cycle_anchor: 1768109968,
            billing_cycle_anchor_config: null,
            billing_mode: {
                flexible: { proration_discounts: "included" },
                type: "flexible",
                updated_at: 1768109928,
            },
            billing_thresholds: null,
            cancel_at: null,
            cancel_at_period_end: false,
            canceled_at: null,
            cancellation_details: { comment: null, feedback: null, reason: null },
            collection_method: "charge_automatically",
            created: 1768109968,
            currency: "eur",
            customer: "cus_Tlp125sTOhHPfE",
            customer_account: null,
            days_until_due: null,
            default_payment_method: "pm_1SoHN5A4zKrgX9zsRqzpQctO",
            default_source: null,
            default_tax_rates: [],
            description: null,
            discounts: [],
            ended_at: null,
            invoice_settings: { account_tax_ids: null, issuer: { type: "self" } },
            items: {
                object: "list",
                data: [[Object]],
                has_more: false,
                total_count: 1,
                url: "/v1/subscription_items?subscription=sub_1SoHN8A4zKrgX9zsVRER5MB7",
            },
            latest_invoice: "in_1SoHN6A4zKrgX9zs058ckKQ6",
            livemode: false,
            metadata: {},
            next_pending_invoice_item_invoice: null,
            on_behalf_of: null,
            pause_collection: null,
            payment_settings: {
                payment_method_options: {
                    acss_debit: null,
                    bancontact: null,
                    card: [Object],
                    customer_balance: null,
                    konbini: null,
                    payto: null,
                    sepa_debit: null,
                    us_bank_account: null,
                },
                payment_method_types: null,
                save_default_payment_method: "off",
            },
            pending_invoice_item_interval: null,
            pending_setup_intent: null,
            pending_update: null,
            plan: {
                id: "price_1SoEbiA4zKrgX9zsSMX3YBOK",
                object: "plan",
                active: true,
                amount: 2999,
                amount_decimal: "2999",
                billing_scheme: "per_unit",
                created: 1768099342,
                currency: "eur",
                interval: "month",
                interval_count: 1,
                livemode: false,
                metadata: {},
                meter: null,
                nickname: null,
                product: "prod_TlmAMbojbwDJb9",
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: "licensed",
            },
            quantity: 1,
            schedule: null,
            start_date: 1768109968,
            status: "active",
            test_clock: null,
            transfer_data: null,
            trial_end: null,
            trial_settings: { end_behavior: { missing_payment_method: "create_invoice" } },
            trial_start: null,
        },
    },
    livemode: false,
    pending_webhooks: 1,
    request: { id: null, idempotency_key: "ae3e5d30-b309-4896-95a1-2b5912f50f1a" },
    type: "customer.subscription.created",
}
