const _ = {
    id: "evt_1SoHdNA4zKrgX9zsVBpi3mZa",
    object: "event",
    api_version: "2025-12-15.clover",
    created: 1768110977,
    data: {
        object: {
            id: "in_1SoHWQA4zKrgX9zsjpiARHW2",
            object: "invoice",
            account_country: "FR",
            account_name: "Environnement de test Super Panda",
            account_tax_ids: null,
            amount_due: 2999,
            amount_overpaid: 0,
            amount_paid: 0,
            amount_remaining: 2999,
            amount_shipping: 0,
            application: null,
            attempt_count: 1,
            attempted: true,
            auto_advance: true,
            automatic_tax: {
                disabled_reason: null,
                enabled: false,
                liability: null,
                provider: null,
                status: null,
            },
            automatically_finalizes_at: null,
            billing_reason: "subscription_cycle",
            collection_method: "charge_automatically",
            created: 1773207568,
            currency: "eur",
            custom_fields: null,
            customer: "cus_Tlp125sTOhHPfE",
            customer_account: null,
            customer_address: {
                city: null,
                country: "JP",
                line1: null,
                line2: null,
                postal_code: null,
                state: null,
            },
            customer_email: "itsuki.enjoy@gmail.com",
            customer_name: "itsuki",
            customer_phone: null,
            customer_shipping: null,
            customer_tax_exempt: "none",
            customer_tax_ids: [],
            default_payment_method: null,
            default_source: null,
            default_tax_rates: [],
            description: null,
            discounts: [],
            due_date: null,
            effective_at: 1773208230,
            ending_balance: 0,
            footer: null,
            from_invoice: null,
            hosted_invoice_url:
                "https://invoice.stripe.com/i/acct_1So9qLA4zKrgX9zs/test_YWNjdF8xU285cUxBNHpLcmdYOXpzLF9UbHBBZjV3eWVvYkttUkpJcXZzUzhtTkFWbklwdnBiLDE1ODY1MTc3Nw02008TP02suX?s=ap",
            invoice_pdf:
                "https://pay.stripe.com/invoice/acct_1So9qLA4zKrgX9zs/test_YWNjdF8xU285cUxBNHpLcmdYOXpzLF9UbHBBZjV3eWVvYkttUkpJcXZzUzhtTkFWbklwdnBiLDE1ODY1MTc3Nw02008TP02suX/pdf?s=ap",
            issuer: { type: "self" },
            last_finalization_error: null,
            latest_revision: null,
            lines: {
                object: "list",
                data: [[Object]],
                has_more: false,
                total_count: 1,
                url: "/v1/invoices/in_1SoHWQA4zKrgX9zsjpiARHW2/lines",
            },
            livemode: false,
            metadata: {},
            next_payment_attempt: 1773368048,
            number: "NCPSTB7T-0005",
            on_behalf_of: null,
            parent: {
                quote_details: null,
                subscription_details: { metadata: {}, subscription: "sub_1SoHN8A4zKrgX9zsVRER5MB7" },
                type: "subscription_details",
            },
            payment_settings: {
                default_mandate: null,
                payment_method_options: {
                    acss_debit: null,
                    bancontact: null,
                    card: [Object],
                    customer_balance: null,
                    konbini: null,
                    payto: null,
                    sepa_debit: null,
                    us_bank_account: null,
                },
                payment_method_types: null,
            },
            period_end: 1773207568,
            period_start: 1770788368,
            post_payment_credit_notes_amount: 0,
            pre_payment_credit_notes_amount: 0,
            receipt_number: null,
            rendering: null,
            shipping_cost: null,
            shipping_details: null,
            starting_balance: 0,
            statement_descriptor: null,
            status: "open",
            status_transitions: {
                finalized_at: 1773208230,
                marked_uncollectible_at: null,
                paid_at: null,
                voided_at: null,
            },
            subtotal: 2999,
            subtotal_excluding_tax: 2999,
            test_clock: "clock_1SoHPBA4zKrgX9zst4ohXKBV",
            total: 2999,
            total_discount_amounts: [],
            total_excluding_tax: 2999,
            total_pretax_credit_amounts: [],
            total_taxes: [],
            webhooks_delivered_at: 1773207568,
        },
    },
    livemode: false,
    pending_webhooks: 1,
    request: { id: null, idempotency_key: null },
    type: "invoice.payment_failed",
}
