// customer.subscription.updated
const _event = {
    id: "evt_1SowygA4zKrgX9zsNiidiihd",
    object: "event",
    api_version: "2025-12-15.clover",
    created: 1768269901,
    data: {
        object: {
            id: "sub_1SowlQA4zKrgX9zsJhyVMikw",
            object: "subscription",
            application: null,
            application_fee_percent: null,
            automatic_tax: { disabled_reason: null, enabled: false, liability: null },
            billing_cycle_anchor: 1769478766,
            billing_cycle_anchor_config: null,
            billing_mode: {
                flexible: { proration_discounts: "included" },
                type: "flexible",
                updated_at: 1768269075,
            },
            billing_thresholds: null,
            cancel_at: null,
            cancel_at_period_end: false,
            canceled_at: null,
            cancellation_details: { comment: null, feedback: null, reason: null },
            collection_method: "charge_automatically",
            created: 1768269080,
            currency: "usd",
            customer: "cus_TmVmLi6UHIcljG",
            customer_account: null,
            days_until_due: null,
            default_payment_method: "pm_1SowmfA4zKrgX9zsTYAXgtzf",
            default_source: null,
            default_tax_rates: [],
            description: null,
            discounts: [],
            ended_at: null,
            invoice_settings: { account_tax_ids: null, issuer: { type: "self" } },
            items: {
                object: "list",
                data: [[Object]],
                has_more: false,
                total_count: 1,
                url: "/v1/subscription_items?subscription=sub_1SowlQA4zKrgX9zsJhyVMikw",
            },
            latest_invoice: "in_1SowyeA4zKrgX9zsB1YdMmcr",
            livemode: false,
            metadata: {},
            next_pending_invoice_item_invoice: null,
            on_behalf_of: null,
            pause_collection: null,
            payment_settings: {
                payment_method_options: {
                    acss_debit: null,
                    bancontact: null,
                    card: [Object],
                    customer_balance: null,
                    konbini: null,
                    payto: null,
                    sepa_debit: null,
                    us_bank_account: null,
                },
                payment_method_types: null,
                save_default_payment_method: "off",
            },
            pending_invoice_item_interval: null,
            pending_setup_intent: null,
            pending_update: null,
            plan: {
                id: "price_1SoY5AA4zKrgX9zsYJ9ZgNJ7",
                object: "plan",
                active: true,
                amount: 1500,
                amount_decimal: "1500",
                billing_scheme: "per_unit",
                created: 1768174204,
                currency: "usd",
                interval: "month",
                interval_count: 1,
                livemode: false,
                metadata: {},
                meter: null,
                nickname: "Pro (Monthly)",
                product: "prod_Tm6H25iEKp9ZRs",
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: "licensed",
            },
            quantity: 1,
            schedule: "sub_sched_1Soww0A4zKrgX9zsgyUQfFuT",
            start_date: 1768269080,
            status: "active",
            test_clock: "clock_1SowrzA4zKrgX9zsIo0Jke9c",
            transfer_data: null,
            trial_end: 1769478766,
            trial_settings: { end_behavior: { missing_payment_method: "create_invoice" } },
            trial_start: 1768269322,
        },
        previous_attributes: {
            items: { data: [[Object]] },
            latest_invoice: "in_1Sows2A4zKrgX9zshJVxstdT",
            plan: {
                id: "price_1SoY5AA4zKrgX9zsntheCB3M",
                amount: 14400,
                amount_decimal: "14400",
                interval: "year",
                nickname: "Pro (Annual)",
            },
        },
    },
    livemode: false,
    pending_webhooks: 1,
    request: { id: null, idempotency_key: null },
    type: "customer.subscription.updated",
}
