// customer.subscription.updated
const _event = {
    id: "evt_1Soww1A4zKrgX9zsOf0Gng8I",
    object: "event",
    api_version: "2025-12-15.clover",
    created: 1768269736,
    data: {
        object: {
            id: "sub_1SowlQA4zKrgX9zsJhyVMikw",
            object: "subscription",
            application: null,
            application_fee_percent: null,
            automatic_tax: { disabled_reason: null, enabled: false, liability: null },
            billing_cycle_anchor: 1769478766,
            billing_cycle_anchor_config: null,
            billing_mode: {
                flexible: { proration_discounts: "included" },
                type: "flexible",
                updated_at: 1768269075,
            },
            billing_thresholds: null,
            cancel_at: null,
            cancel_at_period_end: false,
            canceled_at: null,
            cancellation_details: { comment: null, feedback: null, reason: null },
            collection_method: "charge_automatically",
            created: 1768269080,
            currency: "usd",
            customer: "cus_TmVmLi6UHIcljG",
            customer_account: null,
            days_until_due: null,
            default_payment_method: "pm_1SowmfA4zKrgX9zsTYAXgtzf",
            default_source: null,
            default_tax_rates: [],
            description: null,
            discounts: [],
            ended_at: null,
            invoice_settings: { account_tax_ids: null, issuer: { type: "self" } },
            items: {
                object: "list",
                data: [[Object]],
                has_more: false,
                total_count: 1,
                url: "/v1/subscription_items?subscription=sub_1SowlQA4zKrgX9zsJhyVMikw",
            },
            latest_invoice: "in_1Sows2A4zKrgX9zshJVxstdT",
            livemode: false,
            metadata: {},
            next_pending_invoice_item_invoice: null,
            on_behalf_of: null,
            pause_collection: null,
            payment_settings: {
                payment_method_options: {
                    acss_debit: null,
                    bancontact: null,
                    card: [Object],
                    customer_balance: null,
                    konbini: null,
                    payto: null,
                    sepa_debit: null,
                    us_bank_account: null,
                },
                payment_method_types: null,
                save_default_payment_method: "off",
            },
            pending_invoice_item_interval: null,
            pending_setup_intent: null,
            pending_update: null,
            plan: {
                id: "price_1SoY5AA4zKrgX9zsntheCB3M",
                object: "plan",
                active: true,
                amount: 14400,
                amount_decimal: "14400",
                billing_scheme: "per_unit",
                created: 1768174204,
                currency: "usd",
                interval: "year",
                interval_count: 1,
                livemode: false,
                metadata: {},
                meter: null,
                nickname: "Pro (Annual)",
                product: "prod_Tm6H25iEKp9ZRs",
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: "licensed",
            },
            quantity: 1,
            schedule: "sub_sched_1Soww0A4zKrgX9zsgyUQfFuT",
            start_date: 1768269080,
            status: "active",
            test_clock: "clock_1SowrzA4zKrgX9zsIo0Jke9c",
            transfer_data: null,
            trial_end: 1769478766,
            trial_settings: { end_behavior: { missing_payment_method: "create_invoice" } },
            trial_start: 1768269322,
        },
        previous_attributes: { schedule: null },
    },
    livemode: false,
    pending_webhooks: 1,
    request: { id: null, idempotency_key: "d62ff3c0-a861-47a7-9496-1563a49d8b80" },
    type: "customer.subscription.updated",
}

const _subscription = {
    id: "sub_1SowlQA4zKrgX9zsJhyVMikw",
    object: "subscription",
    application: null,
    application_fee_percent: null,
    automatic_tax: { disabled_reason: null, enabled: false, liability: null },
    billing_cycle_anchor: 1769478766,
    billing_cycle_anchor_config: null,
    billing_mode: {
        flexible: { proration_discounts: "included" },
        type: "flexible",
        updated_at: 1768269075,
    },
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: { comment: null, feedback: null, reason: null },
    collection_method: "charge_automatically",
    created: 1768269080,
    currency: "usd",
    customer: "cus_TmVmLi6UHIcljG",
    customer_account: null,
    days_until_due: null,
    default_payment_method: "pm_1SowmfA4zKrgX9zsTYAXgtzf",
    default_source: null,
    default_tax_rates: [],
    description: null,
    discounts: [],
    ended_at: null,
    invoice_settings: { account_tax_ids: null, issuer: { type: "self" } },
    items: {
        object: "list",
        data: [
            {
                id: "si_TmVnT1xhfVBBzk",
                object: "subscription_item",
                billing_thresholds: null,
                created: 1768269080,
                current_period_end: 1801014766,
                current_period_start: 1769478766,
                discounts: [],
                metadata: {},
                plan: {
                    id: "price_1SoY5AA4zKrgX9zsntheCB3M",
                    object: "plan",
                    active: true,
                    amount: 14400,
                    amount_decimal: "14400",
                    billing_scheme: "per_unit",
                    created: 1768174204,
                    currency: "usd",
                    interval: "year",
                    interval_count: 1,
                    livemode: false,
                    metadata: {},
                    meter: null,
                    nickname: "Pro (Annual)",
                    product: "prod_Tm6H25iEKp9ZRs",
                    tiers_mode: null,
                    transform_usage: null,
                    trial_period_days: null,
                    usage_type: "licensed",
                },
                price: {
                    id: "price_1SoY5AA4zKrgX9zsntheCB3M",
                    object: "price",
                    active: true,
                    billing_scheme: "per_unit",
                    created: 1768174204,
                    currency: "usd",
                    custom_unit_amount: null,
                    livemode: false,
                    lookup_key: null,
                    metadata: {},
                    nickname: "Pro (Annual)",
                    product: "prod_Tm6H25iEKp9ZRs",
                    recurring: [Object],
                    tax_behavior: "unspecified",
                    tiers_mode: null,
                    transform_quantity: null,
                    type: "recurring",
                    unit_amount: 14400,
                    unit_amount_decimal: "14400",
                },
                quantity: 1,
                subscription: "sub_1SowlQA4zKrgX9zsJhyVMikw",
                tax_rates: [],
            },
        ],
        has_more: false,
        total_count: 1,
        url: "/v1/subscription_items?subscription=sub_1SowlQA4zKrgX9zsJhyVMikw",
    },
    latest_invoice: "in_1Sows2A4zKrgX9zshJVxstdT",
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
        payment_method_options: {
            acss_debit: null,
            bancontact: null,
            card: { network: null, request_three_d_secure: "automatic" },
            customer_balance: null,
            konbini: null,
            payto: null,
            sepa_debit: null,
            us_bank_account: null,
        },
        payment_method_types: null,
        save_default_payment_method: "off",
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
        id: "price_1SoY5AA4zKrgX9zsntheCB3M",
        object: "plan",
        active: true,
        amount: 14400,
        amount_decimal: "14400",
        billing_scheme: "per_unit",
        created: 1768174204,
        currency: "usd",
        interval: "year",
        interval_count: 1,
        livemode: false,
        metadata: {},
        meter: null,
        nickname: "Pro (Annual)",
        product: "prod_Tm6H25iEKp9ZRs",
        tiers_mode: null,
        transform_usage: null,
        trial_period_days: null,
        usage_type: "licensed",
    },
    quantity: 1,
    schedule: "sub_sched_1Soww0A4zKrgX9zsgyUQfFuT",
    start_date: 1768269080,
    status: "active",
    test_clock: "clock_1SowrzA4zKrgX9zsIo0Jke9c",
    transfer_data: null,
    trial_end: 1769478766,
    trial_settings: { end_behavior: { missing_payment_method: "create_invoice" } },
    trial_start: 1768269322,
}

const _schedule = {
    "id": "sub_sched_1Soww0A4zKrgX9zsgyUQfFuT",
    "object": "subscription_schedule",
    "application": null,
    "billing_migration": null,
    "billing_mode": {
        "flexible": {
            "proration_discounts": "included",
        },
        "type": "flexible",
        "updated_at": 1770947882,
    },
    "canceled_at": null,
    "completed_at": null,
    "created": 1770947882,
    "current_phase": null,
    "customer": "cus_TmVmLi6UHIcljG",
    "customer_account": null,
    "default_settings": {
        "application_fee_percent": null,
        "automatic_tax": {
            "disabled_reason": null,
            "enabled": false,
            "liability": null,
        },
        "billing_cycle_anchor": "automatic",
        "billing_thresholds": null,
        "collection_method": "charge_automatically",
        "default_payment_method": "pm_1SowmfA4zKrgX9zsTYAXgtzf",
        "default_source": null,
        "description": null,
        "invoice_settings": {
            "account_tax_ids": null,
            "days_until_due": null,
            "issuer": {
                "type": "self",
            },
            "rendering": null,
        },
        "on_behalf_of": null,
        "transfer_data": null,
    },
    "end_behavior": "release",
    "initial_billing_cycle_anchor": null,
    "livemode": false,
    "metadata": {},
    "phases": [
        {
            "add_invoice_items": [],
            "application_fee_percent": null,
            "billing_cycle_anchor": null,
            "billing_thresholds": null,
            "collection_method": null,
            "coupon": null,
            "currency": "usd",
            "default_payment_method": null,
            "default_tax_rates": [],
            "description": null,
            "discounts": [],
            "end_date": 1801014766,
            "invoice_settings": null,
            "items": [
                {
                    "billing_thresholds": null,
                    "discounts": [],
                    "metadata": {},
                    "plan": "price_1SoY5AA4zKrgX9zsntheCB3M",
                    "price": "price_1SoY5AA4zKrgX9zsntheCB3M",
                    "quantity": 1,
                    "tax_rates": [],
                },
            ],
            "metadata": {},
            "on_behalf_of": null,
            "proration_behavior": "create_prorations",
            "start_date": 1769478766,
            "transfer_data": null,
            "trial_end": null,
        },
        {
            "add_invoice_items": [],
            "application_fee_percent": null,
            "billing_cycle_anchor": null,
            "billing_thresholds": null,
            "collection_method": null,
            "coupon": null,
            "currency": "usd",
            "default_payment_method": null,
            "default_tax_rates": [],
            "description": null,
            "discounts": [],
            "end_date": 1801014767,
            "invoice_settings": null,
            "items": [
                {
                    "billing_thresholds": null,
                    "discounts": [],
                    "metadata": {},
                    "plan": "price_1SoY5AA4zKrgX9zsYJ9ZgNJ7",
                    "price": "price_1SoY5AA4zKrgX9zsYJ9ZgNJ7",
                    "quantity": 1,
                    "tax_rates": [],
                },
            ],
            "metadata": {},
            "on_behalf_of": null,
            "proration_behavior": "create_prorations",
            "start_date": 1801014766,
            "transfer_data": null,
            "trial_end": null,
        },
    ],
    "released_at": 1801014767,
    "released_subscription": "sub_1SowlQA4zKrgX9zsJhyVMikw",
    "renewal_interval": null,
    "status": "released",
    "subscription": null,
    "test_clock": "clock_1SowrzA4zKrgX9zsIo0Jke9c",
}
