drop type if exists price_behavior cascade;

create type price_behavior as enum('one_time', 'recurring');

drop type if exists recurring_interval cascade;

create type recurring_interval as enum('day', 'week', 'month', 'year');

drop table if exists subscription_plans cascade;

create table subscription_plans (
  id bigint not null generated by default as identity primary key,
  -- when user payment fail, donw grade plan to this
  downgrade_plan_id bigint default null references subscription_plans (id) on delete set null,
  price_id text not null,
  product_id text not null,
  currency text not null,
  -- The unit amount in cents to be charged
  unit_amount bigint not null,
  recurring_interval recurring_interval not null,
  recurring_interval_count bigint not null,
  -- null for no trial
  trial_period_days bigint,
  title text not null,
  description text not null,
  -- null for unlimited
  behavior price_behavior not null default 'recurring',
  is_active boolean not null,
  is_default boolean not null default false,
  unique (price_id, product_id)
);

insert into
  subscription_plans (
    id,
    price_id,
    product_id,
    currency,
    unit_amount,
    recurring_interval,
    recurring_interval_count,
    trial_period_days,
    title,
    description,
    is_active
  )
values
  (
    1,
    'price_1SoY5AA4zKrgX9zscje8hTVI',
    'prod_Tm6H25iEKp9ZRs',
    'usd',
    0,
    'week',
    1,
    null,
    'Free',
    '',
    true
  );


-- Pro (Monthly)
insert into
  subscription_plans (
    id,
    downgrade_plan_id,
    price_id,
    product_id,
    currency,
    unit_amount,
    recurring_interval,
    recurring_interval_count,
    trial_period_days,
    title,
    description,
    is_active,
    is_default
  )
values
  (
    2,
    1,
    'price_1SoY5AA4zKrgX9zsYJ9ZgNJ7',
    'prod_Tm6H25iEKp9ZRs',
    'usd',
    1500,
    'month',
    1,
    14,
    'Pro (Monthly)',
    '',
    true,
    true
  );

-- Pro (Annually)
insert into
  subscription_plans (
    id,
    downgrade_plan_id,
    price_id,
    product_id,
    currency,
    unit_amount,
    recurring_interval,
    recurring_interval_count,
    trial_period_days,
    title,
    description,
    is_active
  )
values
  (
    3,
    1,
    'price_1SoY5AA4zKrgX9zsntheCB3M',
    'prod_Tm6H25iEKp9ZRs',
    'usd',
    14400,
    'year',
    1,
    14,
    'Pro (Annually)',
    '',
    true
  );

-- Enable RLS
alter table subscription_plans enable row level security;

create policy "all user can view subscription_plans" on subscription_plans for
select
  to authenticated using (true);

-- enable real time postgres changes
alter publication supabase_realtime
add table subscription_plans;
